### ISSUE TITLE
Remove allocation

### ISSUE THREAD

**Issue by fulmicoton** [JDemler/rust-stemmers#1]
That would be awesome if there was an API that avoided all alloc. (Maybe by passing a `&mut String`)

**Comment by JDemler** [comment]
Do you mean it would be awesome for performance or usability?
The bottleneck for these stemmers is probably not the occasional allocation of a byte vector,  which happens in `SnoballEnv::replace_s`.
(But I didn't measure, please correct me if I'm wrong.)

From a usability point of view it might make sense. Probably you got the string out of `to_lowercase()` anyway.
In that case I would propose the following function definition:

```rust
    pub fn stem(&self, input: String) -> String
```

**Comment by fulmicoton** [comment]
I said that for performance reasons,  thinking that the allocation would be more important than it actually is.

	Running Time	Self		Symbol Name
	91144.0ms  100.0%	11213.0	 	rust_stemmers::snowball::algorithms::english::_stem::hf5ccdd2a2099486e
	52767.0ms   57.8%	52767.0	 	 rust_stemmers::snowball::snowball_env::SnowballEnv::find_among_b::h169cfefc809b647c
	10338.0ms   11.3%	10338.0	 	 rust_stemmers::snowball::snowball_env::SnowballEnv::find_among::hf0fd5aa89d9b4639
	10089.0ms   11.0%	10089.0	 	 rust_stemmers::snowball::snowball_env::SnowballEnv::in_grouping::h0cfe0a5a8443999f
	3367.0ms    3.6%	1247.0	 	 rust_stemmers::snowball::snowball_env::SnowballEnv::replace_s::h5479b1961231d19e
	1865.0ms    2.0%	1865.0	 	 rust_stemmers::snowball::snowball_env::SnowballEnv::out_grouping::heeda8d1a8202f4f5
	738.0ms    0.8%	108.0	 	 rust_stemmers::snowball::algorithms::english::__r_shortv::h691e42a8753ff4c7
	593.0ms    0.6%	593.0	 	 rust_stemmers::snowball::snowball_env::SnowballEnv::in_grouping_b::h35c2a9c71d55d493
	90.0ms    0.0%	90.0	 	 rust_stemmers::snowball::snowball_env::SnowballEnv::out_grouping_b::he4ee0529287523f1
	58.0ms    0.0%	0.0	 	 <Unknown Address>
	26.0ms    0.0%	26.0	 	 DYLD-STUB$$memcpy

**Comment by JDemler** [comment]
Cool, thank you for actually looking into it.

The Snowball language and its stemmers probably haven't been build with performance in mind.
Anyways, if you find any angle one could attack to make them faster, let me know.

I guess this issue is resolved. Feel free to reopen if this is not the case!

**Comment by fulmicoton** [comment]
Do you think there is room to improve performance?
I'm experimenting with using `rust-stemmers` in tantivy by the way.

**Comment by JDemler** [comment]
Actually I never looked into it because in my case the indexing in general is not the performance bottleneck.

The good thing about the snowball project is its extensive test suite. 
So basically you can try and break things and when you're wrong you will know.

My first guess would be, that to really improve these stemmers performance-wise something radical would be needed. Maybe optimizations on compiler level. But a low hanging fruit could be the `find_among` and `find_among_b` methods.

Happy to hear that you want to use the stemmers in tantivy. Good Luck!
How did you stem before? 
Did you have a performance problem with that method as well?

**Comment by fulmicoton** [comment]
Tantivy does not have stemming at all for the moment. It still lacks a lot of very basic functionalities. Maybe in 6 months it will be a usable engine :)
